name: SwiftLint

on: [push]

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      
      - name: Install SwiftLint
        run: brew install swiftlint

      - name: Run SwiftLint
        run: |
          set - o pipefail
          swiftlint lint | sed -E 's/^(.*):([0-9]+):([0-9]+): (warning|error|[^:]+): (.*)/::\4 title=Lint error,file=\1,line=\2,col=\3::\5\n\1:\2:\3/'