name: SwiftLint

on:
  push:
    branches:
      - '*'

jobs:
  swiftlint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Swift
        uses: actions/setup-swift@v2

      - name: Run SwiftLint
        run: swiftlint