name: TestFlight

on:
  push:
    paths:
      - '.github/workflows/*.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  swiftlint:
    name: SwiftLint Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.2.1
    
  test_server_debug:
    name: Upload TestServerDebug Scheme
    runs-on: macos-latest
    needs: swiftlint
    if: github.event_name == 'workflow_dispatch'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install Bundler
          run: gem install bundler
        - name: Install Dependencies for Bundler
          run: bundle install
        - name: Update fastlane
          run: bundle update fastlane
        - name: Upload TestSchemeDebug Scheme
          run: bundle exec fastlane test

  release_server_debug:
    name: Upload ReleaseServerDebug Scheme
    runs-on: macos-latest
    needs: swiftlint
    if: github.event_name == 'workflow_dispatch'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install Bundler
          run: gem install bundler
        - name: Install Dependencies for Bundler
          run: bundle install
        - name: Update fastlane
          run: bundle update fastlane
        - name: Upload ReleaseServerDebug Scheme
          run: bundle exec fastlane release_debug

  release_server_prod:
    name: Upload ReleaseServerProd Scheme
    runs-on: macos-latest
    needs: swiftlint
    if: github.event_name == 'workflow_dispatch'
    steps:
        - name: Checkout repository
          uses: actions/checkout@v4
        - name: Install Bundler
          run: gem install bundler
        - name: Install Dependencies for Bundler
          run: bundle install
        - name: Update fastlane
          run: bundle update fastlane
        - name: Upload ReleaseSchemeProd Scheme
          run: bundle exec fastlane release_prod